<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <PropertyGroup>
        <ContainsTests>true</ContainsTests>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <FirelySdkVersion>6.1.1</FirelySdkVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Moq" Version="4.18.4" />
        <PackageReference Include="FluentAssertions" Version="7.2.2" />
        <PackageReference Include="MessagePack" Version="3.1.4" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="MSTest.TestFramework" Version="3.8.2" />
        <PackageReference Include="MSTest.TestAdapter" Version="3.8.2" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="10.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Firely.Fhir.Packages" Version="5.0.2" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <SignAssembly>True</SignAssembly>
        <DelaySign>true</DelaySign>
        <AssemblyOriginatorKeyFile>..\..\FirelyValidatorPubKey.snk</AssemblyOriginatorKeyFile>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>ExperimentalApi;SDK0001;</NoWarn>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>
