<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0</TargetFrameworks>
		<AssemblyName>Benchmarks</AssemblyName>
		<RootNamespace>Firely.Fhir.Validation.Benchmarks</RootNamespace>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
        <DefineConstants>PROJECT;VALSDK6</DefineConstants>
	</PropertyGroup>
    
	<ItemGroup>
        <Content Include="TestData\DocumentComposition\*.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="TestData\**\*.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
	</ItemGroup>

    <ItemGroup Condition="$(DefineConstants.Contains('PROJECT'))">
        <ProjectReference Include="..\..\src\Firely.Fhir.Validation.R4\Firely.Fhir.Validation.R4.csproj" />
    </ItemGroup>
    
    <PropertyGroup Condition="$(DefineConstants.Contains('VALSDK5'))">
        <ValidatorVersion Condition="'$(ValidatorVersion)' == ''">2.7.0</ValidatorVersion>
        <SDKVersion Condition="'$(SDKVersion)' == ''">5.12.1</SDKVersion>
    </PropertyGroup>

    <PropertyGroup Condition="$(DefineConstants.Contains('VALSDK6'))">
        <ValidatorVersion Condition="'$(ValidatorVersion)' == ''">2.8.0-alpha-20250905.1</ValidatorVersion>
        <SDKVersion Condition="'$(SDKVersion)' == ''">6.0.0-rc2-20250915.4</SDKVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Condition="'$(ValidatorVersion)' != ''" Include="Firely.Fhir.Validation.R4" Version="$(ValidatorVersion)" />
        <PackageReference Condition="'$(SDKVersion)' != ''" Include="Hl7.Fhir.Specification.Data.R4" Version="$(SDKVersion)" />
    </ItemGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<SignAssembly>True</SignAssembly>
		<DelaySign>true</DelaySign>
		<AssemblyOriginatorKeyFile>..\..\FirelyValidatorPubKey.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
	
	

</Project>

