<Project Sdk="Microsoft.NET.Sdk">
  
  <Import Project="..\..\firely-validator-api-tests.props" />

  <PropertyGroup>
    <AssemblyName>Firely.Fhir.Validation.Tests</AssemblyName>
  </PropertyGroup>
 
  <ItemGroup>
    <ProjectReference Include="..\..\src\Firely.Fhir.Validation\Firely.Fhir.Validation.csproj" />
<!--    <ProjectReference Include="..\Benchmarks\Benchmarks.csproj" />-->
    <PackageReference Include="Hl7.Fhir.R5" Version="$(FirelySdkVersion)" />
    <PackageReference Update="Firely.Fhir.Packages" Version="4.9.2-alpha-build-20250414-3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
